# =====================================================================
# MACROS
# =====================================================================

ext_if = "vtnet0"
bridge_if = "bridge0"
vlan_net = "11.0.0.0/16"

# =====================================================================
# GLOBAL OPTIONS
# =====================================================================

# Block packets by dropping them.
set block-policy drop

# To prevent unnecessary filtering on local packets, skip the loopback interface.
set skip on lo0

# To prevent fragmentation attacks, normalize and reassemble packets.
scrub in all

# =====================================================================
# NAT CONFIGURATION
# =====================================================================

match out on $ext_if inet from $vlan_net to any nat-to ($ext_if)

# =====================================================================
# DUMMYNET TRAFFIC SHAPING
# =====================================================================
# dnctl pipe 10 config bw 10Mbit/s mask dst-ip 0xffffffff
# dnctl pipe 20 config bw 10Mbit/s mask src-ip 0xffffffff

# Upload throttling for vLAN hosts
match in on $bridge_if inet from $vlan_net to any dnpipe 10

# Download throttling for vLAN hosts
match in on $ext_if inet from any to $vlan_net dnpipe 20

# =====================================================================
# DEFAULT FILTERS
# =====================================================================

# By default, block all incoming traffic and log it for monitoring.
block in log on $ext_if from any

# Allow all outgoing traffic and keep state for return packets.
pass out all keep state

# =====================================================================
# EXTERNAL INTERFACE FILTERS
# =====================================================================

# Allow SSH from any source IP to the external interface
pass in quick on $ext_if proto tcp from any to ($ext_if) port 22 keep state

# Allow ICMP
pass in quick on $ext_if inet proto icmp icmp-type { echoreq, unreach }
pass in quick on $ext_if inet6 proto icmp6 icmp6-type { \
    neighbrsol, neighbradv, \
    routersol, routeradv, \
    echoreq, unreach \
}
