# Filesystem

zfs_enable="YES"
devfs_enable="YES"

# Networking

ifconfig_DEFUALT="DHCP"
ifconfig_vtnet0_ipv6="inet6 accept_rtadv"

cloned_interfaces="bridge0"
ifconfig_bridge0="inet 11.0.0.1 netmask 255.255.0.0 up"

pf_enable="YES"
pf_rules="/etc/pf.conf"

# SSH daemone

sshd_enable="YES"

# Linux compat

linux_enable="YES"

# Network time protocol

ntpd_enable="YES"
ntpd_sync_on_start="YES"

# Other

moused_nondefault_enable="NO"
dumpdev="AUTO"
