# Network routing

net.inet.ip.forwarding="1"

# Packet filtering

net.pf.filter_local="1"
net.link.bridge.pfil_bridge="0"
net.link.bridge.pfil_only="1"
net.link.epair.max_threads="0"

# Default jail privileges

security.jail.enforce_statfs="2"
security.jail.allow_raw_sockets="0"
security.jail.set_hostname_allowed="0"
security.jail.socket_unixiproute_only="1"
security.jail.sysvipc_allowed="0"
security.jail.chflags_allowed="0"

# Disable coredumps to prevent resource exhaustion

kern.coredump="0"
